version: "3.5"

services:
  enrolling.api.test:
    entrypoint:
      - dotnet
      - test
      - --results-directory
      - /tests
      - --logger
      - trx;LogFileName=/tests/enrolling-unit-test-results.xml
      - --collect:"XPlat Code Coverage"
