name: WebStatus

on:
  push:
    paths:
    - "src/Web/WebStatus/**"
    - ".github/workflows/webstatus.yml"
    - "eSchool.sln"
    - "build/dotnet/**"
    - "src/Directory.Build.props"
    - "docker-compose.yml"
    - "docker-compose.override.yml"
    - "docker-compose.dcproj"
    - "docker-compose-test.yml"
    - "docker-compose-test.override.yml"
  pull_request:
    paths:
    - "src/Web/WebStatus/**"
    - ".github/workflows/webstatus.yml"
    - "eSchool.sln"
    - "build/dotnet/**"
    - "src/Directory.Build.props"
    - "docker-compose.yml"
    - "docker-compose.override.yml"
    - "docker-compose.dcproj"
    - "docker-compose-test.yml"
    - "docker-compose-test.override.yml"

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: docker compose
      run: docker-compose build webstatus
